# Generated by Django 5.2 on 2025-04-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='todos_pedidos',
            field=models.TextField(max_length=500),
        ),
    ]
